### ISSUE TITLE
The input query string is modified by compress_comp

### ISSUE THREAD

**Issue by c-zhou** [thegenemyers/FASTK#12]
Hello Gene,

https://github.com/thegenemyers/FASTK/blob/25277f0d4debd8483498d010f545785ad1e24f90/libfastk.c#L648-L650

should line 648-650 of libfastk.c be
```
c = s1[0];
d = s2[0];
e = s3[0];
```

Chenxi

**Comment by thegenemyers** [comment]
Oh yes, good catch and apologies.  I have pushed an update to github.
    Best,
       Gene

**Comment by c-zhou** [comment]
Thanks Gene. I will close this issue now.

Best,
Chenxi
