### ISSUE TITLE
haplex output ktab

### ISSUE THREAD

**Issue by wheaton5** [thegenemyers/FASTK#4]
Hi Gene,

Just digging into this. Looks great so far. Can you make Haplex output a ktab file as well as a text file? I'm wanting to get a set of het kmer pairs and then run those with some modimized homozygous kmers run through the profiler so that I can better categorize het kmer pairs. Or if there is a way to go from the text output to a .ktab that would be good as well.

Thanks,
Haynes

**Comment by thegenemyers** [comment]
Simply turn the output of Haplex into a .fasta file of the k-mers and then give it to FastK again.
The only caveat is that the pairs will no longer be together as tables are always sorted.

Not quite sure what you are wanting to effect in the end, maybe we should discuss on zoom.  I'm
reasonably available and work weekends.

I was also thinking that Haplex and Homex are in themselves projects that maybe should have
their own repo.  This by way of suggesting that we could make a Haplex like first stage to your
work in such a repo.

**Comment by richarddurbin** [comment]
Currently, after building the set of haplex kmers, Haynes is going through each read again to find them in the reads, testing for the presence of each position in a hash table.

I suggested to him that if he built a ktab file of them then he could use your profiling function to indicate where they are - the profile would have zeros except where there was a haplex kmer.  So he could rapidly run along each profile ignoring zeros, and only look up the haplex kmers in his table.  This could mean a hundred-fold fewer cache lookups.  The hope is that making the profiles against the sparse ktab is more efficient than a hash lookup on each read base position, but even if not it would use all your efficient and robust threaded code to do a lot of the heavy lifting.

**Comment by wheaton5** [comment]
I thought of this after submitting this issue. This should work for me. Thanks.

Best,
Haynes

**Comment by thegenemyers** [comment]
Haynes, I added a -H option (for Haynes :-)) that is undocumented but is a beta for you to consider.
It produces the k-mers in haplo pairs in *sorted* order prefaced by an id (an identifier for a pair/triple/quad)
and the het base of this k-mer of the pair.  I could go further and make a table of these with the id replacing
the count.  Then one could take this table to produce a relative profile against say the pacbio reads or
Hi-C reads -- the profiles would then be 0 except where there is a het k-mer and the "count" would be the
id of the het.  In this way one could trivially scan the profiles to build the linkage graph.
Worth talking about?   At a minimum you'd get a table in a more direct manner.

**Comment by richarddurbin** [comment]
This sounds good.  

I am not sure what you mean by the “het base”.  I don’t see much point in having different offset positions for the variable base - we only want one het kmer pair per heterozygous site, which is achieved by requiring the middle base to be the variable base.

I also thought about faking the id into the depth field in the table and hence on the profile, to eliminate the lookup step.  But I thought that would not work because you limited your depths to 16 bit, and there will likely be more than 64k het kmers.

**Comment by thegenemyers** [comment]
Richard, a listing of the pairs is only sorted by the first k-mer of the pair.  The 2nd (or 3rd or 4th) k-mers are not
in alpha-order.  If you put then in alpha order then you no longer have the pairing.  So you need to attache an
id for each pair to each k-mer of the pair.  While I can get the variant base from the k-mer, I included it in the id
as one will want to know which of the kmers it is just from the profile (thus completely avoiding the need to look
at the sequence of a profiled read).  -- Gene

**Comment by wheaton5** [comment]
I think the regular het kmer output is fine. I can use that to remember pairings. haplex could either also output a ktab or I could just convert it into a fasta file and run Fastk again as you suggested. Faking the kmer id into the depth shouldnt be necessary as just knowing the location should reduce my lookups by 10x-100x.
