### ISSUE TITLE
bc trim option to take as many ints as source files?

### ISSUE THREAD

**Issue by wheaton5** [thegenemyers/FASTK#9]
For linked reads we want to trim 23 bases from R1 but not from R2. Right now I'm making two calls and then doing a Logex 'result = (A |+ B)' R1 R2.

This would be fine except for min counts on 2 files vs one file. Making a trim of 23 for both is okay except you do lose a fair amount of data. I can make this change and make a pull request if you are willing to take pull requests. Or i can just make this change in my forked version.

**Comment by thegenemyers** [comment]
Let's discuss this afternoon on zoom as I don't quite understand.  My 
thought was that
you are building a relative profile of these reads relative to the 
Haplex table to find
where the het- and hom-mers are in each of these paired Illumina reads.  
So one can
be prefix trimmed, the other not, and the relative profiles paired in 
the ensuing scan.
    -- Gene

**Comment by wheaton5** [comment]
I think we resolved this issue.
